name: base
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python
  - numpy
  - pandas
  - scipy
  - PyHamcrest
  - matplotlib
  - scikit-learn
  - pytorch-cpu=0.4.1=py37_cpu_1
  - torchvision-cpu=0.2.1=py37_1
  - pip:
    - nbgitpuller
    - sphinx-gallery
    - pandas
    - pyro-ppl
    - SPARQLWrapper
    - quilt
    - graphviz==0.10.1
    - libarchive-c==2.8
    - msgpack==0.5.6
    - pyro-ppl==0.2.1
    - tables==3.4.4
    - torch==0.4.1
    - torchvision==0.2.1
