name: base
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.6
  - numpy
  - pandas
  - scipy
  - PyHamcrest
  - matplotlib
  - scikit-learn
  - pytorch-cpu=0.4.1
  - torchvision-cpu=0.2.1
  - jupyter
  - pip:
    - nbgitpuller
    - sphinx-gallery
    - pandas
    - pyro-ppl
    - SPARQLWrapper
    - quilt
    - graphviz==0.10.1
    - libarchive-c==2.8
    - msgpack==0.5.6
    - pyro-ppl==0.2.1
    - tables==3.4.4
    - torch==0.4.1
    - torchvision==0.2.1
    - ipywidgets
    - jupyter_contrib_nbextensions
    - spacy
    - SPARQLWrapper
    - https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.0.0/en_core_web_sm-2.0.0.tar.gz#en_core_web_sm

