name: case-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - pytorch-cpu
  - torchvision-cpu
  - pip:
    - nbgitpuller
    - sphinx-gallery
    - pandas
    - pyro-ppl
    - SPARQLWrapper
    - quilt
- matplotlib
